### ISSUE TITLE
v2 Pest Control Truck Endpoint Empty

### ISSUE THREAD

**Issue by misterhamm-bzs** [zachspiel/bobs-burgers-api#6]
Looks like v1 still works but the v2 endpoint just returns an empty array.

- https://bobsburgers-api.herokuapp.com/pestControlTruck/
- https://bobsburgers-api.herokuapp.com/v2/pestControlTruck/

**Comment by zachspiel** [comment]
I definitely broke this with the v2 release, I appreciate you letting me know! I will work on a fix and have it up as soon as possible.

**Comment by zachspiel** [comment]
Hello, the latest release [2.1.0](https://github.com/zachspiel/bobs-burgers-api/releases/tag/2.1.0) now includes a fix for this issue which has been deployed. 

Please re-open this issue or create a new issue if something is still not working. Thank you!
